# This file is generated by edalize.
# Microsemi Tcl Script
# libero

new_project -location {./impl} -name libero-project -project_description {} -block_mode 0 -standalone_peripheral_initialization 0 -instantiate_in_smartdesign 1 -ondemand_build_dh 1 -linked_files_root_dir_env {} -hdl {VERILOG} -family {Polarfire} -die {MPF300TS_ES} -package {FCG1152} -speed {-1}  -die_voltage {1.0} -part_range {IND} -adv_options {IO_DEFT_STD:LVCMOS 1.8V} -adv_options {RESTRICTPROBEPINS:1} -adv_options {RESTRICTSPIPINS:0} -adv_options {SYSTEM_CONTROLLER_SUSPEND_MODE:0} -adv_options {TEMPR:IND} -adv_options {VCCI_1.2_VOLTR:EXT} -adv_options {VCCI_1.5_VOLTR:EXT} -adv_options {VCCI_1.8_VOLTR:EXT} -adv_options {VCCI_2.5_VOLTR:EXT} -adv_options {VCCI_3.3_VOLTR:EXT} -adv_options {VOLTR:IND}
set_device -family {Polarfire} -die {MPF300TS_ES} -package {FCG1152} -speed {-1} -die_voltage {1.0}  -part_range {IND} -adv_options {IO_DEFT_STD:LVCMOS 1.8V} -adv_options {RESTRICTPROBEPINS:1} -adv_options {RESTRICTSPIPINS:0} -adv_options {SYSTEM_CONTROLLER_SUSPEND_MODE:0} -adv_options {TEMPR:IND} -adv_options {VCCI_1.2_VOLTR:EXT} -adv_options {VCCI_1.5_VOLTR:EXT} -adv_options {VCCI_1.8_VOLTR:EXT} -adv_options {VCCI_2.5_VOLTR:EXT} -adv_options {VCCI_3.3_VOLTR:EXT} -adv_options {VOLTR:IND}

import_files \
        -convert_EDN_to_HDL 0 \
        -hdl_source { vlog_file.v } \
        -hdl_source { vlog05_file.v } \
        -hdl_source { vhdl_file.vhd } \
        -hdl_source { vhdl_lfile } \
        -hdl_source { vhdl2008_file } \

build_design_hierarchy
set_root -module {top_module::work}
build_design_hierarchy

run_tool -name {SYNTHESIZE}
run_tool -name {PLACEROUTE}
run_tool -name {GENERATEPROGRAMMINGDATA}
run_tool -name {GENERATEPROGRAMMINGFILE}
