# This file is generated by Edalize.
# Microsemi Tcl Script
# FPExpress

puts "----------------- Opening Job file libero-test-all ------------------------------"
create_job_project \
	-job_project_location ./prj \
	-job_file ./prj/libero-test-all.job \
         -overwrite 0

puts "----------------- Programming device -------------------------------------"
set_programming_action -name MPF300TS_ES -action {PROGRAM}
run_selected_actions -prog_spi_flash 0 -disable_prog_design 0
