# This file is generated by Edalize.
# Microsemi Tcl Script
# Libero

open_project -file {./prj/libero-test-all.prjx}

run_tool -name {SYNTHESIZE}
run_tool -name {PLACEROUTE}
run_tool -name {GENERATEPROGRAMMINGDATA}
run_tool -name {GENERATEPROGRAMMINGFILE}

export_prog_job \
    -job_file_name libero-test-all \
    -export_dir ../prj \
    -bitstream_file_type {TRUSTED_FACILITY} \
    -bitstream_file_components {}
