#Auto generated by Edalize

TARGET   := test_vivado_yosys_0

include container_tools.mk

all: $(TARGET).edif


%.blif: yosys.tcl
	$(YOSYS) -l yosys.log -p "tcl $?"
%.json: yosys.tcl
	$(YOSYS) -l yosys.log -p "tcl $?"
%.edif: yosys.tcl
	$(YOSYS) -l yosys.log -p "tcl $?"

clean:
	rm -f $(TARGET).blif $(TARGET).json $(TARGET).edif
