# This file is generated by Edalize.
# Microsemi Tcl Script
# Libero

puts "----------------- Opening project design ------------------------------"
open_project -file {./prj/design.prjx}

run_tool -name {SYNTHESIZE}
run_tool -name {PLACEROUTE}
run_tool -name {GENERATEPROGRAMMINGDATA}


puts "----------------- Exporting Programming Job File -----------------------------"
export_prog_job \
    -job_file_name design \
    -export_dir ./prj \
    -bitstream_file_type {TRUSTED_FACILITY} \
    -bitstream_file_components {}

puts "----------------- Finished building project -----------------------------"

close_project -save 1
