#Auto generated by Edalize

TARGET   := test_vivado_nextpnr_0

all: $(TARGET).fasm

test_vivado_nextpnr_0.json: test_vivado_nextpnr_0.mk
	$(MAKE) -f $<

test_vivado_nextpnr_0.fasm: test_vivado_nextpnr_0.json
	nextpnr-xilinx --chipdb chipdb.bin --xdc top.xdc --json test_vivado_nextpnr_0.json --write test_vivado_nextpnr_0.routed.json --fasm test_vivado_nextpnr_0.fasm

clean:
	rm -f $(TARGET).fasm $(TARGET).routed.json
