#!/usr/bin/env python3
import os
import sys

output_file = sys.argv[2]
with open(output_file, "a"):
    # set the access and modified times to the current time
    os.utime(output_file, None)

with open("ecppack.cmd", "w") as f:
    f.write(" ".join(sys.argv[1:]) + "\n")
