#!/usr/bin/env python3
import os
import sys

output_file = sys.argv[sys.argv.index("--output_file") + 1]

with open(output_file, "a"):
    os.utime(output_file, None)

with open("xc7frames2bit.cmd", "w") as f:
    f.write(" ".join(sys.argv[1:]) + "\n")
