#Auto generated by Edalize

TARGET   := test_symbiflow_nextpnr_fpga_interchange_0

all: $(TARGET).fasm

ifndef INTERCHANGE_SCHEMA_PATH
$(error Environment variable INTERCHANGE_SCHEMA_PATH was not found. It should be set to <fpga-interchange-schema path>/interchange)
endif

XDCS += --xdc top.xdc

test_symbiflow_nextpnr_fpga_interchange_0.json: test_symbiflow_nextpnr_fpga_interchange_0.mk
	$(EDALIZE_LAUNCHER) $(MAKE) -f $<

test_symbiflow_nextpnr_fpga_interchange_0.netlist: test_symbiflow_nextpnr_fpga_interchange_0.json
	$(EDALIZE_LAUNCHER) python -m fpga_interchange.yosys_json --schema_dir $(INTERCHANGE_SCHEMA_PATH) --device xc7a35t.device --top top_module test_symbiflow_nextpnr_fpga_interchange_0.json test_symbiflow_nextpnr_fpga_interchange_0.netlist

test_symbiflow_nextpnr_fpga_interchange_0.phys: test_symbiflow_nextpnr_fpga_interchange_0.netlist
	$(EDALIZE_LAUNCHER) nextpnr-fpga_interchange --chipdb chipdb.bin --package csg324 $(XDCS) --netlist test_symbiflow_nextpnr_fpga_interchange_0.netlist --write test_symbiflow_nextpnr_fpga_interchange_0.routed.json --phys test_symbiflow_nextpnr_fpga_interchange_0.phys --fake_option 1000

test_symbiflow_nextpnr_fpga_interchange_0.fasm: test_symbiflow_nextpnr_fpga_interchange_0.phys
	$(EDALIZE_LAUNCHER) python -m fpga_interchange.fasm_generator --schema_dir $(INTERCHANGE_SCHEMA_PATH) --family xc7 xc7a35t.device test_symbiflow_nextpnr_fpga_interchange_0.netlist test_symbiflow_nextpnr_fpga_interchange_0.phys test_symbiflow_nextpnr_fpga_interchange_0.fasm

clean:
	$(EDALIZE_LAUNCHER) rm -f $(TARGET).json $(TARGET).routed.json $(TARGET).netlist $(TARGET).phys $(TARGET).fasm
