#Auto generated by Edalize

all: test_symbiflow_nextpnr_fpga_interchange_0.blif

test_symbiflow_nextpnr_fpga_interchange_0.blif test_symbiflow_nextpnr_fpga_interchange_0.json test_symbiflow_nextpnr_fpga_interchange_0.edif: edalize_yosys_template.tcl
	$(EDALIZE_LAUNCHER) yosys -l yosys.log -p "tcl edalize_yosys_template.tcl"
