#Auto generated by Edalize

TARGET   := test_symbiflow_nextpnr_fpga_interchange_0

all: $(TARGET).blif


%.blif: edalize_yosys_template.tcl
	$(EDALIZE_LAUNCHER) yosys -l yosys.log -p "tcl $?"
%.json: edalize_yosys_template.tcl
	$(EDALIZE_LAUNCHER) yosys -l yosys.log -p "tcl $?"
%.edif: edalize_yosys_template.tcl
	$(EDALIZE_LAUNCHER) yosys -l yosys.log -p "tcl $?"

clean:
	rm -f $(TARGET).blif $(TARGET).json $(TARGET).edif
