# This file is generated by edalize.

source waiver_file.waiver

source tcl_file.tcl

analyze -f sources.f
elaborate -params { { vlogparam_bool 1 } { vlogparam_int 42 } { vlogparam_str "hello" } } top_module
report_policy -skip_empty_summary_status -compat -output ascentlint.rpt NEW
exit
