--lint_fatal --parse_fatal --rules_config=config.vbl,config2.vbl sv_file.sv
--lint_fatal --parse_fatal --rules_config=config.vbl,config2.vbl vlog_file.v
--lint_fatal --parse_fatal --rules_config=config.vbl,config2.vbl vlog05_file.v
