#Auto generated by Edalize

TARGET   := test_nextpnr_xilinx

all: $(TARGET).blif


%.blif: test_nextpnr_xilinx.tcl
	yosys -l yosys.log -p "tcl $?"
%.json: test_nextpnr_xilinx.tcl
	yosys -l yosys.log -p "tcl $?"
%.edif: test_nextpnr_xilinx.tcl
	yosys -l yosys.log -p "tcl $?"

clean:
	rm -f $(TARGET).blif $(TARGET).json $(TARGET).edif
